# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kiosk Tech Monthly
email: hardrefresh@kiosk.tm
description: This is a static site!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kiosk.tm" # the base hostname & protocol for your site
github_username:  kiosktm

# Build settings
markdown: kramdown
